language: node_js

sudo: false

node_js:
  # https://github.com/nodejs/LTS
  - "6" # ends April 2019
  - "8" # ends December 2019
  - "10" # ends April 2021

cache:
  directories:
  - node_modules

env:
  global:
    - SAUCE_USERNAME=sinonjs
    - secure: "Rwa8sp0slbhbdDFmxX/taISeINwjATzgITO2BHPymXK8vohP/HnyfbJjU75FT7scHbAy69TemdeFIJjTAp+dxR1j4z0PZv5fqiM9jqgt6lWsav0jSOFQfkmaiB4A9kNZMBBlLi0ynNqjO03pjVWMaMwOX2RtqWQ+XWA+gct1o+4="


before_install:
  - npm config set strict-ssl false
  - npm install coveralls
  # Prevent mochify -> puppeteer install script to run unnecessarily
  - if [ "x$TRAVIS_NODE_VERSION" != "x10" ]; then npm config set ignore-scripts true; fi

before_script:
  # Make npm run work for the script phase:
  - if [ "x$TRAVIS_NODE_VERSION" != "x10" ]; then npm config set ignore-scripts false; fi
  # these build targets only need to run once per build, so let's conserve a few resources
  - if [ "x$TRAVIS_NODE_VERSION" = "x10" ]; then npm run lint; fi
  - if [ "x$TRAVIS_NODE_VERSION" = "x10" ]; then npm run test-headless -- --allow-chrome-as-root; fi
  - if [ "x$TRAVIS_NODE_VERSION" = "x10" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test-cloud; fi

script:
  - npm test

after_success:
  - if [ "x$TRAVIS_NODE_VERSION" = "x10" ]; then npm run test-coverage && cat ./coverage/lcov.info | coveralls lib; fi

git:
  depth: 10
